# Generated by Django 5.2.5 on 2025-09-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supliers',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
