# Generated by Django 5.2.5 on 2025-09-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_category_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='discountconfig',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
