# Generated by Django 5.2.5 on 2025-09-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='supliers',
        ),
        migrations.AlterField(
            model_name='productstock',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
