# Generated by Django 5.2.5 on 2025-09-04 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_category_supliers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountConfig',
        ),
    ]
