# Generated by Django 5.2.5 on 2025-09-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_unitcreate_alter_productstock_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitcreate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='unitcreate',
            table='unit_create',
        ),
    ]
