# Generated by Django 5.2.5 on 2025-09-04 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_unitcreate_is_deleted_alter_unitcreate_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitcreate',
            name='description',
        ),
    ]
