# Generated by Django 5.2.5 on 2025-09-06 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_unitcreate_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstock',
            name='description',
        ),
        migrations.AddField(
            model_name='productstock',
            name='base_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_base_unit', to='inventory.unitcreate'),
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_factor', models.DecimalField(decimal_places=4, help_text="Conversion factor to convert from 'from_unit' to 'to_unit'.", max_digits=10)),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_conversions', to='inventory.unitcreate')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_conversions', to='inventory.unitcreate')),
            ],
            options={
                'db_table': 'unit_conversion',
                'unique_together': {('from_unit', 'to_unit')},
            },
        ),
    ]
