# Generated by Django 5.2.5 on 2025-09-07 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_unittype_alter_productstock_base_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='unittypeconfigurations',
            table='unit_configurations',
        ),
    ]
