# Generated by Django 5.2.5 on 2025-09-07 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_unittypeconfigurations_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unittypeconfigurations',
            name='unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.unittype'),
        ),
    ]
