# Generated by Django 5.2.5 on 2025-09-07 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_unittypeconfigurations_unit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unittypeconfigurations',
            name='quantity',
        ),
    ]
