# Generated by Django 5.2.5 on 2025-09-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_unittypeconfigurations_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('Gram', 'Gram'), ('Dozen', 'Dozen'), ('Liter', 'Liter'), ('Ml', 'Ml'), ('Piece', 'Piece'), ('Box', 'Box'), ('Pack', 'Pack')], default='Piece', max_length=50),
        ),
        migrations.RemoveField(
            model_name='unittypeconfigurations',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='base_unit',
        ),
        migrations.RemoveField(
            model_name='unittypeconfigurations',
            name='product',
        ),
        migrations.DeleteModel(
            name='UnitType',
        ),
        migrations.DeleteModel(
            name='UnitTypeConfigurations',
        ),
    ]
