# Generated by Django 5.2.5 on 2025-09-07 06:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_unitcreate_productstock_base_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'unit_type',
            },
        ),
        migrations.AlterField(
            model_name='productstock',
            name='base_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_base_unit', to='inventory.unittype'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.unittype'),
        ),
        migrations.CreateModel(
            name='UnitTypeConfigurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('conversion_factor', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.productstock')),
                ('unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.unittype')),
            ],
            options={
                'db_table': 'unit_configurations',
            },
        ),
        migrations.DeleteModel(
            name='UnitConversion',
        ),
        migrations.DeleteModel(
            name='UnitCreate',
        ),
    ]
