# Generated by Django 5.2.5 on 2025-09-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_unittype_alter_productstock_base_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unittypeconfigurations',
            name='quantity',
        ),
    ]
