# Generated by Django 5.2.5 on 2025-09-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_remove_unittypeconfigurations_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unittypeconfigurations',
            old_name='conversion_factor',
            new_name='conversion_per_unit',
        ),
        migrations.AddField(
            model_name='unittypeconfigurations',
            name='conversion_unit_name',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
