# Generated by Django 5.2.5 on 2025-09-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_rename_conversion_factor_unittypeconfigurations_conversion_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittypeconfigurations',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
