# Generated by Django 5.2.5 on 2025-09-07 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_unittypeconfigurations_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unittypeconfigurations',
            name='conversion_unit_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversion_unit_configurations', to='inventory.unittype'),
        ),
    ]
