# Generated by Django 5.2.5 on 2025-09-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_unittypeconfigurations_conversion_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unittypeconfigurations',
            name='conversion_unit_name',
            field=models.CharField(default='pieces', max_length=50),
        ),
    ]
