# Generated by Django 5.2.5 on 2025-08-20 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_rename_quantity_productstock_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_Name', models.CharField(default=None, max_length=50)),
                ('customer_address', models.CharField(default=None, max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], max_length=50)),
                ('actual_amount', models.IntegerField()),
                ('recived_amount', models.IntegerField()),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'bill',
            },
        ),
        migrations.CreateModel(
            name='BillingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='billing.bill')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_bill', to='inventory.productstock')),
            ],
            options={
                'db_table': 'billing_Items',
            },
        ),
    ]
